# Source - https://stackoverflow.com/a/72334752
# Posted by itsMont, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-06, License - CC BY-SA 4.0

server.port=9526
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
